# Generated by Django 6.1.1 on 2026-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text='Unique app identifier on Google Play (e.g. com.whatsapp)', max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name. If empty, filled by crawler on first run.', max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='Official Play Store category', max_length=100, null=True)),
                ('is_messaging_app', models.BooleanField(default=False, help_text='Flags whether this app needs network (pcap) analysis')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag; crawler only processes active apps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
