# Generated by Django 6.1.1 on 2026-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_iranian_app',
            field=models.BooleanField(default=False, help_text='Whether this app targets the Iranian market; used by the crawler to select the appropriate Play Store region/locale.'),
        ),
    ]
